name: ProjectTerra iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET 9 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.100

    - name: Install iOS Workload
      run: |
        dotnet workload install ios
        dotnet workload restore ProjectTerra.iOS/ProjectTerra.iOS.csproj

    - name: Set Xcode Version
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer

    - name: Build iOS App
      run: |
        dotnet build ProjectTerra.iOS/ProjectTerra.iOS.csproj \
          -c Release \
          /p:MtouchLink=SdkOnly \
          /p:EnableCodeSigning=false
    
  
